version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "2345:5432"
    env_file: ./environments/local.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file: ./environments/local.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
  web:
